name: lite-techne-microservices

services:
  litetechne-auth:
    image: litetechne-auth
    container_name: lite-techne-auth
    environment:
      SYNCHRONIZE: true
      LOGGING: true
      JWT_SECRET: secretodetest
    depends_on:
      bd-lite-techne-auth:
        condition: service_healthy
    ports:
      - "3000:3000"

  litetechne-catalog:
    image: litetechne-catalog
    container_name: lite-techne-catalog
    environment:
      SYNCHRONIZE: true
      LOGGING: true
      JWT_SECRET: secretodetest
    depends_on:
      bd-lite-techne-catalog:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3001:3001"

  litetechne-inventory:
    image: litetechne-inventory
    container_name: lite-techne-inventory
    environment:
      SYNCHRONIZE: true
      LOGGING: true
      JWT_SECRET: secretodetest
    depends_on:
      bd-lite-techne-inventory:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3002:3002"

  litetechne-report:
    image: litetechne-report
    container_name: lite-techne-report
    environment:
      SYNCHRONIZE: true
      LOGGING: true
      JWT_SECRET: secretodetest
    depends_on:
      bd-lite-techne-report:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3003:3003"